version: '3.9'
services:
  kestra:
    image: kestra/kestra:latest
    command: server standalone
    restart: unless-stopped
    volumes:
      - kestra_storage:/app/storage
      - ./flows:/app/flows
      - ./.kestra/config:/app/config
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      KESTRA_LOG_LEVEL: info

volumes:
  kestra_storage:
